# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
auto_detect_solc = true
block_timestamp = 100_000_000
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000
# Configure remappings
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  'solmate/=lib/solmate/src/',
  'ds-test/=lib/ds-test/src/',
  'std/=lib/forge-std/src/',
  '@unifap-v2/=lib/unifap-v2/src/',
  'sol-tuts/=lib/sol-tuts/src/',
]

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 10_000
